### ISSUE TITLE
Issue in eval_policy.py

### ISSUE THREAD

**Issue by ishandotsh** [KevinHuang8/DATT#5]
I trained the main policy from the paper using:
`python train_policy.py -n policy -c DATT_config.py -t trajectory_fbff --ref mixed_ref -ts 25000000 --checkpoint True`
then running the eval_policy.py script:
`python eval_policy.py -n policy -c DATT_config.py -t trajectory_fbff --ref random_zigzag -s 500 --viz True`
gives this error:

30674
TIME HORIZON:  10
USING FB:  True
init_ref 1 <class 'DATT.learning.refs.random_zigzag.RandomZigzag'>
/home/ishan/miniconda3/envs/datt/lib/python3.10/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/
wind field [ 1.32135683  0.25522908 -0.5859985 ]
mass 1.0
k 0.4
dict_keys(['return_motor_info'])
Traceback (most recent call last):
  File "/home/ishan/python/DATT/learning/eval_policy.py", line 267, in <module>
    eval()
  File "/home/ishan/python/DATT/learning/eval_policy.py", line 124, in eval
    obs, rewards, dones, info = evalenv.step(act, return_motor_info=True)
  File "/home/ishan/python/DATT/learning/base_env.py", line 46, in step_and_save
    return step_func(*args, **kwargs)
TypeError: BaseQuadsimEnv.step() got an unexpected keyword argument 'return_motor_info'

**Comment by Omikaa** [comment]
same issue
