### ISSUE TITLE
Regarding disturbance (wind) application in simulation 

### ISSUE THREAD

**Issue by SapanaChaudhary** [KevinHuang8/DATT#7]
Hello! 

I was wondering how the disturbance force application is modeled in simulation in DATT? 
It is  a translation force acting upon drone center of mass (like the first function below)?
Or does it also include a pitching and rolling effect by means of torque application (second function below)? 
Also, where can I find the corresponding physics/disturbance functions in your code base? 

Thanks in advance! 

![image](https://github.com/KevinHuang8/DATT/assets/14027764/8e495d56-f9e9-484d-98c1-0eefc8d32bd4)

**Comment by KevinHuang8** [comment]
the wind is modeled as a translational force, like you mentioned

the relevant code is found here: https://github.com/KevinHuang8/DATT/blob/42ddfc8ccf1afe416c50b8e6d37864d70ce18af0/quadsim/sim.py#L140
